server:
  port: 9091
  shutdown: graceful
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 20s
    threads:
      max: 200
      min-spare: 10
spring:
  application:
    name: menu-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5431/menu_service_db
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 12
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${external.keycloak-url}
          jwk-set-uri: ${external.jwk-set-url}

eureka:
  client:
    service-url:
      defaultZone: ${external.discovery-service-url}
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true

external:
  discovery-service-url: http://localhost:8761/eureka/
  zipkin-endpoint: http://localhost:9411/api/v2/spans
  keycloak-url: http://keycloak:8080/realms/cloud-java
  jwk-set-url: http://keycloak:8080/realms/cloud-java/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: ${external.zipkin-endpoint}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  menu-create:
    summary: Создание блюда меню
    description: |
      Создает блюдо и сохраняет его в базе данных.
      Возвращает информацию о созданном блюде, включая его идентификатор.
  menu-delete:
    summary: Удаление блюда.
    description: Удаляет блюдо по идентификатору.
  menu-update:
    summary: Обновление блюда.
    description: Обновляет блюдо в соответствии с переданными в теле запроса параметрами.
  menu-get:
    summary: Получение блюда.
    description: Возвращает информацию о блюде по его идентификатору.
  menu-list-get:
    summary: Получение списка блюд.
    description: |
      Возвращает список блюд из указанной категории. Список может быть пустым, если в категории нет блюд.
      Доступные категории: breakfast, lunch, dinner, drinks, snacks, salads.
      Список отсортирован в соответствии с указанным параметром сортировки.
      Доступные параметры сортировки: 
      az - сортирует по названию в алфавитном порядке
      za - сортирует по названию в обратном порядке
      price_asc - сортирует по возрастанию цены
      price_desc - сортирует по убыванию цены
      date_asc - сортирует по дате создания меню в порядке возрастания
      date_desc - сортирует по дате создания меню в порядке убывания
  menu-info:
    summary: Получение информации о цене и доступности блюд.
    description: |
      Возвращает информацию о цене, названии и доступности блюда в ресторане. Если блюда нет в ресторане,
      его цена представлена null значением. Несмотря на то, что семантика запроса полностью
      соответствует HTTP GET запросу, используется именно POST, так как в теле запроса может
      быть передан длинный список названий блюд.
  response:
    createOk: Блюдо создано успешно
    createConflict: Блюдо не было создано, так как блюдо с таким названием уже существует в базе.
    createBadRequest: Блюдо не было создано, так как запрос содержит ошибки. Подробнее в сообщении об ошибке.
    deleteNoContent: Блюдо с идентификатором более не хранится в базе данных.
    updateOk: Блюдо успешно обновлено.
    notFound: Блюдо с таким идентификатором не найдено в базе данных.
    updateBadRequest: Блюдо не было обновлено, так как запрос содержит ошибки. Подробнее в сообщении об ошибке.
    getOk: Блюдо успешно найдено.
    getListOk: Список блюд по категории успешно сформирован.
    getListBadRequest: Список блюд невозможно сформировать, так как в запросе некорректные параметры.
    getMenuInfoBadRequest: Информацию о блюдах невозможно сформировать, так как в запросе некорректные параметры (список названий пуст).
    getMenuInfoOk: Информация о блюдах успешно сформирована.