server:
  port: 9092
  shutdown: graceful
  netty:
    connection-timeout: 3s
    idle-timeout: 20s

spring:
  application:
    name: orders-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:15432/order_service_db
    pool:
      max-create-connection-time: 2s
      initial-size: 6
      max-size: 12
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:15432/order_service_db
  kafka:
    bootstrap-servers: localhost:9097
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

eureka:
  client:
    service-url:
      defaultZone: ${external.discovery-service-url}
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true

kafkaprops:
  order-dispatch-topic: v1.orders_dispatch
  nack-sleep-duration: 100ms

external:
  discovery-service-url: http://localhost:8761/eureka/
  menu-service-url: "http://menu-service"
  menu-info-path: "/v1/menu-items/menu-info"
  default-timeout: 2s
  retry-backoff: 100ms
  retry-count: 5
  retry-jitter: 0.75

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  submit-order:
    summary: Создание заказа пользователем.
    description: |
      Создает новый заказ на имя пользователя. 
      Названия блюд передаются в теле запроса. 
      В случае отсутствия какого-либо блюда в Menu Service, возвращается 500-ая ошибка.
  get-orders:
    summary: Получение списка заказов пользователя.
    description: Возвращает список заказов пользователя, отсортированный по дате создания заказа.
  response:
    submitOk: Заказ успешно сформирован.
    submitBadRequest: Заказ не был сформирован из-за ошибки в запросе. Подробнее в сообщении об ошибке.
    submitNotFound: Заказ не был сформирован, так как часть блюд отсутствует в ресторане.
    submitInternalError: Заказ не был сформирован из-за ошибки на сервере. Подробнее в сообщении об ошибке.
    getOk: Список заказов пользователя сформирован.
    getBadRequest: Не удалось сформировать список заказов пользователя из-за ошибки в параметрах запроса.